addresses:
  - address: "0x91c92feec285dd56d506f9eb4ddc2eb7cd6e71dd"
    name: validator0
    network: calibration
  - address: "0x7287922457de4095e7b7e8cdcddf6be48c3f1f4a"
    name: validator1
    network: calibration
  - address: "0x91c92feec285dd56d506f9eb4ddc2eb7cd6e71dd"
    name: validator0
    network: testnet-v2
  - address: "0x7287922457de4095e7b7e8cdcddf6be48c3f1f4a"
    name: validator1
    network: testnet-v2
networks:
  - name: calibration
    rpc_endpoint: https://rpc.ankr.com/filecoin_testnet
  - name: testnet-v2
    rpc_endpoint: https://evm-testnet-v2-validator-0.3box.io
update_interval_seconds: 60
static_bearer_token: ${STATIC_BEARER_TOKEN}
